// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cujuxcbnqwnwydgllezu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1anV4Y2JucXdud3lkZ2xsZXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDc3MDcsImV4cCI6MjA2NDA4MzcwN30.hrhI5dyEV3Y4t6v5wSi9PTtLVXcrQyHDRJ6HHNhZ-mU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);